accelerator: null
accumulate_grad_batches: 1
amp_backend: native
amp_level: O2
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 16
benchmark: false
check_val_every_n_epoch: 1
checkpoint_callback: true
default_hp_metric: false
default_root_dir: null
deterministic: true
devices: null
distributed_backend: null
dropout: 0
early_stopping_patience: 10
exposure_dataset: imagenet_irma
fast_dev_run: false
flush_logs_every_n_steps: 100
gpus: 5,
gradient_clip_algorithm: norm
gradient_clip_val: 0.0
imagenet: false
ipus: null
irma_length: false
learning_rate: 0.0003
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
log_gpu_memory: null
logger: true
max_epochs: 8
max_steps: null
max_time: null
min_epochs: null
min_steps: null
model_checkpoint: null
model_id: null
move_metrics_to_cpu: false
multigpu: null
multiple_trainloader_mode: max_size_cycle
no_finding: false
no_finding_images: true
num_classes: 14
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
num_workers: 8
ood: false
ood_nofinding: false
ood_weight: 0.5
optim: adam
outlier_exposure: true
overfit_batches: 0.0
patience: 1
pin_memory: true
plugins: null
pos_weight: null
precision: 32
prepare_data_per_node: true
pretrained: true
process_position: 0
profiler: null
progress_bar_refresh_rate: null
reload_dataloaders_every_epoch: false
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
reproduction: false
resume_from_checkpoint: null
sample: null
scheduler: plateau
seed: 0
size: 224
split: original
stochastic_weight_avg: false
sync_batchnorm: false
tensorboard_dir: run
terminate_on_nan: false
tpu_cores: null
track_grad_norm: -1
truncated_bptt_steps: null
val_check_interval: 1.0
weight_decay: 0.0001
weights_save_path: null
weights_summary: top
